### ISSUE TITLE
FALL TODO LIST

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#1]
## Week 1 (Searching 1)
- [x] Lecture Problem Laser Phones
- [x] Lecture Problem Catch That Cow
- [x] Challenge Problem Scales
- [x] Challenge Problem Tractor
- [x] Challenge Problem What's Up With Gravity?
- [x] Challenge Problem The Castle
## Week 2 (Searching 2)
- [x] Lecture Problem Maze1
- [x] Challenge Problem The Trough Game
- [x] Challenge Problem Climbing Wall
- [x] Challenge Problem Fliptile
## Week 3 (Data Structures 1)
- [x] Lecture Problem Best Parenthesis
- [x] Challenge Problem Look Up
- [x] Challenge Problem Time Travel
- [x] Challenge Problem Artificial Lake
## Week 4 (Data Structures 2)
- [x] Lecture Problem Auto Complete
- [x] Lecture Problem Game of Lines
- [x] Challenge Problem Perimeter
- [ ] Challenge Problem Flower Pot
- [ ] Challenge Problem The Bessie Shuffle
## Week 5 (Graphs 1)
- [x] Lecture Problem The Loathesome Hay Baler
- [ ] Challenge Problem Starry Night
- [ ] Challenge Problem Unlocking Blocks
- [ ] Challenge Problem Tractor
## Week 6 (Review Exam)
- [x] Exam Problem Mud Puddles
- [ ] Exam Problem Bessie Slows Down
- [ ] Exam Problem Tea Time
## Week 7 (Graphs 2)
- [x] Lecture Problem Bessie Come Home
- [x] Lecture Problem Clear and Present Danger
- [ ] Challenge Problem Luxury River Cruise
- [ ] Challenge Problem Chocolate Milk
- [ ] Challenge Problem Frame Up
## Week 8 (Graphs 3)
- [x]  Lecture Problem Minimum Spanning Tree
- [x] Lecture Problem Watering the Fields
- [x] Challenge Problem water
- [ ] Challenge Problem Superbull
- [x] Challenge Problem Power Failure
- [ ] Challenge Problem Road Block
## Week 9 (Graphs 4)
- [x] Lecture Problem Dijkstra
- [x] Lecture Problem Chocolate Giving
- [ ] Challenge Problem Photo
- [x] Challenge Problem Silver Cow Party
- [ ] Challenge problem Traffic Lights
## Week 10 (Graphs 5)
- [x] Lecture Problem Cow Contest
- [x] Lecture Problem Hide and Seek
- [ ] Challenge Problem Bovine Alliance
- [ ] Challenge Problem Total Flow
- [ ] Challenge Problem Cross Country Skiing
## Week 11 (Graphs 6)
- [ ] Lecture Problem Minimum Spanning Tree
- [ ] Lecture Problem Dijkstra's
- [ ] Lecture Problem Chocolate Giving
## Week 12 (Final Exam)
- [ ] Exam Problem Backward Digit Sums
- [ ] Exam Problem Best Spot
- [ ] Exam Problem Cow Routing
