### ISSUE TITLE
SPRING TODO LIST

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#15]
## Week 1 (DP I)
- [x] Lecture Problem Selfish Graze
- [x] Challenge Problem Profits
- [ ] Challenge Problem Running
- [ ] Challenge Problem A Game

## Week 2 (DP II)
- [x] Lecture Problem Cow Pie Treasures
- [x] Lecture Problem Cow Hopscotch
- [ ] Challenge Problem Round Numbers
- [ ] Challenge Problem The County Fair
- [ ] Challenge Problem Marathon

## Week 3 (DP III)
- [x] Lecture Problem Longest Increasing Subsequence
- [x] Lecture Problem Subset Sums
- [ ] Challenge Problem Angry Cows
- [ ] Challenge Problem Meeting Time
- [ ] Challenge Problem Cow Travelling

## Week 4 (DP IV)
- [x] Lecture Problem Knapsack
- [x] Lecture Problem Cow Cash
- [x] Lecture Problem Bessie's Weight Problem
- [ ] Challenge Problem Mooo Moo
- [ ] Challenge Problem Candy
- [ ] Challenge Problem Bale Share

## Week 5 (DP V)
- [ ] Lecture Problem Longest Common Subsequence
- [ ] Lecture Problem Longest Common Substring
- [ ] Lecture Problem String Edit Distance

## Week 6 (Review Exam)
- [ ] Exam Problem Bulls and Cows
- [ ] Exam Problem Eating Together
- [ ] Exam Problem Stamps II

## Week 7 (DP VI)
- [ ] Lecture Problem Longest Common Subsequence 2
- [ ] Lecture Problem Charm Bracelet

## Week 8 (DP VII)
- [ ] Lecture Problem Breed Proximity
- [ ] Lecture Problem Building a Fence
- [ ] Lecture Problem Grazing II

## Week 9 (Greedy Methods I)
- [ ] Lecture Problem Chocolate Buying
- [ ] Lecture Problem Soda Machine
- [ ] Lecture Problem Sand Castle

## Week 10 (Greedy Methods II)
- [ ] Lecture Problem Word Power
- [ ] Lecture Problem Mountain Watching
- [ ] Lecture Problem Test Taking

## Week 11 (Computational Geometry)
- [ ] Lecture Problem Perimeter
- [ ] Lecture Problem Crazy Fences

## Week 12 (Final Exam)
- [ ] Exam Problem Buying Hay
- [ ] Exam Problem Cow Jog
- [ ] Exam Problem The Longest Prefix
