### ISSUE TITLE
Week 1 Todo List

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#2]
## Week 1 (Searching 1)
- [x] Lecture Problem lphone
- [x] Lecture Problem catchcow
- [x] Challenge Problem scales
- [x] Challenge Problem tractor
- [ ] Challenge Problem gravity
- [x] Challenge Problem wall
