### ISSUE TITLE
Week 2 Todo List

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#3]
## Week 2 (Searching 2)
- [x] Lecture Problem maze1
- [x] Challenge Problem trough
- [x] Challenge Problem castle
- [x] Challenge Problem fliptile

**Comment by varmichelle** [comment]
done
