### ISSUE TITLE
Week 3 Todo List

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#4]
## Week 3 (Data Structures 1)
- [x] Lecture Problem paren
- [ ] Challenge Problem lookup
- [ ] Challenge Problem ttravel
- [ ] Challenge Problem alake
