### ISSUE TITLE
Week 5 Todo List

### ISSUE THREAD

**Issue by varmichelle** [bananabot1024/USACO#6]
## Week 5 (Graphs 1)
- [x] Lecture Problem baler
- [ ] Challenge Problem starry
- [ ] Challenge Problem unlock
- [ ] Challenge Problem tractor2
